# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(max_length=20)),
                ('title', models.TextField(max_length=100)),
                ('editor_name', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=100000)),
                ('document_link', models.TextField(max_length=10000)),
                ('cover_image', models.ImageField(blank=True, upload_to=b'images')),
            ],
        ),
    ]
